name: drivetools

services:
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/letsencrypt/live/${DOMAIN}/privkey.pem
    networks:
      - external-network
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - DOMAIN=${DOMAIN}
      - CLIENT_DOMAIN=${CLIENT_DOMAIN}
      - CLIENT_PORT=${CLIENT_PORT}
      - SERVICE_DOMAIN=${SERVICE_DOMAIN}
      - SERVICE_PORT=${SERVICE_PORT}
      - SERVICE_API_PATH=${SERVICE_API_PATH}

  client:
    container_name: ${CLIENT_DOMAIN}
    build:
      context: ./client
      dockerfile: ../docker/Dockerfile.client.light
      args:
        - SERVICE_URL=${PROTOCOL}://${DOMAIN}${SERVICE_API_PATH}
        - CLIENT_ID=${CLIENT_ID}
        - CLIENT_PORT=${CLIENT_PORT}
    restart: always
    expose:
      - ${CLIENT_PORT}
    networks:
      - external-network
    environment:
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - CLIENT_DOMAIN=${CLIENT_DOMAIN}
      - CLIENT_PORT=${CLIENT_PORT}
      - CLIENT_ID=${CLIENT_ID}
      - SERVICE_API_PATH=${SERVICE_API_PATH}

  service:
    container_name: ${SERVICE_DOMAIN}
    build:
      context: ./service
      dockerfile: ../docker/Dockerfile.service.light
      args:
        SERVICE_PORT: ${SERVICE_PORT}
    restart: always
    depends_on:
      - ${DATABASE_DOMAIN}
    expose:
      - ${SERVICE_PORT}
    networks:
      - external-network
      - secure-network
    environment:
      - SERVICE_DOMAIN=${SERVICE_DOMAIN}
      - SERVICE_PORT=${SERVICE_PORT}
      - DATABASE_DOMAIN=${DATABASE_DOMAIN}
      - PG_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_DOMAIN}:${DATABASE_PORT}/${POSTGRES_DB}

  database:
    container_name: ${DATABASE_DOMAIN}
    image: postgres:11
    restart: always
    expose:
      - ${DATABASE_PORT}
    volumes:
      - database:/var/lib/postgresql/data
      - ./postgres/initpg.sh:/docker-entrypoint-initdb.d/initpg.sh
    networks:
      - secure-network
    environment:
      - DATABASE_DOMAIN=${DATABASE_DOMAIN}
      - DATABASE_PORT=${DATABASE_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  database:

networks:
  external-network:
    driver: bridge
  secure-network:
    driver: bridge

  # client:
  #   container_name: ${CLIENT_DOMAIN}
  #   build:
  #     context: ../${REPO_NAME_BASE}.${CLIENT_DOMAIN}
  #     dockerfile: ../${REPO_NAME_BASE}.production/docker/Dockerfile.client
  #     args:
  #       - VITE_CLIENT_ID=${VITE_CLIENT_ID}
  #   ports:
  #     - "${CLIENT_PORT}:${CLIENT_PORT}"
  #   restart: always
  #   networks:
  #     - external-network
  #   environment:
  #     REPO_NAME_BASE: ${REPO_NAME_BASE}
  #     CLIENT_DOMAIN: ${CLIENT_DOMAIN}
  #     CLIENT_PORT: ${CLIENT_PORT}
  #     VITE_CLIENT_ID: ${VITE_CLIENT_ID}